server:
  port: 10000
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:10000/eureka/
spring:
  application:
    name: ptCMSeureka